version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker: # Docker でステップを実行します
      - image: circleci/node:12.16.3
    working_directory: "~/output"
    steps:
      - run:
          name: yarn lint ja
          command: yarn textlint ./FusicTechBlog/rails-vue-calendar/rails-vue-calendar.md --config ./.textlintrc --fix
