version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker: # Docker でステップを実行します
      - image: circleci/node:12.16.3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: yarn install
          command: yarn install
      - save_cache:
          paths:
            - ~/.cache/yarn
          key: OutPut-{{ checksum "yarn.lock" }}
      - run:
          name: Rails + Nuxt で Todo アプリを Docker 環境で開発する
          command: yarn textlint ./FusicTechBlog/rails-vue-calendar/rails-vue-calendar.md --config ./.textlintrc
      - run:
          name: Golang + ServerlessFramework (APIGateway + Lambda + DynamoDB)を使用して簡易的なアプリを作ってみた
          command: yarn textlint ./FusicTechBlog/AdventCalendar-vue-calendar/AdventCalendar-vue-calendar.md --config ./.textlintrc
      - run:
          name: WebAPI Design
          command: yarn textlint ./FusicTechBlog/webAPIdesign/webAPIdesign.md --config ./.textlintrc

      - run:
          name: OpenAPI で作成した API 定義書から Mock Server を起動してみた
          command: yarn textlint ./FusicTechBlog/webAPIdesign/webAPIdesign.md --config ./.textlintrc
